eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicle
          uri: http://localhost:9095
          predicates:
              - Path=/vehicle/**
        - id: parking
          uri: http://localhost:9096
          predicates:
            - Path=/parking/**
        - id: booking
          uri: http://localhost:9097
          predicates:
            - Path=/booking/**
        - id: payment
          uri: http://localhost:9098
          predicates:
            - Path=/payment/**