eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: VehicleS1
          uri: http://localhost:9095
          predicates:
            - Path=/vehicle/**
        - id: ParkingS1
          uri: http://localhost:9096
          predicates:
            - Path=/parking/**
        - id: BookingS3
          uri: http://localhost:9097
          predicates:
            - Path=/booking/**
        - id: PaymentS4
          uri: http://localhost:9098
          predicates:
            - Path=/payment/**